# for local testing of the containers

version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=wearenumberone
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  
  backend:
    build: ./backend
    container_name: django-backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

volumes:
  db_data: